[package]
name = "gussing_game_cw"
version = "0.1.0"
authors = ["fight"]
edition = "2018"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.3.14"

[profile.dev]
opt-level = 0
[profile.release]
opt-level = 3
